apiVersion: v1
kind: Pod
metadata:
  name: custom-image-pod
  labels:
    parent: ckad
    type: custom_image
spec:
  containers:
    - name: custom-image
      image: custom_image
      command:
        ["sleep2.0"]
      args: ["10"]