apiVersion: batch/v1
kind: CronJob
metadata:
  name: testing-cron-job

# 3 spec fields - cronJob-jobTemplate-pod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      # job instances
      completions: 3

      # to create the pods required for all the instances at the same time
      parallelism: 3

      # max tries till a success
      backoffLimit: 25
      template:
        spec:
          containers:
            - name: testing-job-container
              image: ubuntu
              command: ["expr"]
              args: ["3+3"]
          restartPolicy: Never
