apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  labels:
    type: deployment
    parent: ckad
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
    # type: Recreate
  template:
    metadata:
      name: testing-pod
      labels:
        type: sample
        parent: ckad
    spec:
      containers:
        - name: nginx-container
          image: nginx
          
  # creates a replicaset
  replicas: 3
  
  selector:
    matchLabels:
      parent: ckad